// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.0
// source: configcenter/v1/config_center.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigCenter_PublishConfig_FullMethodName = "/configcenter.v1.ConfigCenter/PublishConfig"
)

// ConfigCenterClient is the client API for ConfigCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigCenterClient interface {
	PublishConfig(ctx context.Context, in *PublishConfigRequest, opts ...grpc.CallOption) (*PublishConfigResponse, error)
}

type configCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigCenterClient(cc grpc.ClientConnInterface) ConfigCenterClient {
	return &configCenterClient{cc}
}

func (c *configCenterClient) PublishConfig(ctx context.Context, in *PublishConfigRequest, opts ...grpc.CallOption) (*PublishConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishConfigResponse)
	err := c.cc.Invoke(ctx, ConfigCenter_PublishConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigCenterServer is the server API for ConfigCenter service.
// All implementations must embed UnimplementedConfigCenterServer
// for forward compatibility.
type ConfigCenterServer interface {
	PublishConfig(context.Context, *PublishConfigRequest) (*PublishConfigResponse, error)
	mustEmbedUnimplementedConfigCenterServer()
}

// UnimplementedConfigCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigCenterServer struct{}

func (UnimplementedConfigCenterServer) PublishConfig(context.Context, *PublishConfigRequest) (*PublishConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishConfig not implemented")
}
func (UnimplementedConfigCenterServer) mustEmbedUnimplementedConfigCenterServer() {}
func (UnimplementedConfigCenterServer) testEmbeddedByValue()                      {}

// UnsafeConfigCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigCenterServer will
// result in compilation errors.
type UnsafeConfigCenterServer interface {
	mustEmbedUnimplementedConfigCenterServer()
}

func RegisterConfigCenterServer(s grpc.ServiceRegistrar, srv ConfigCenterServer) {
	// If the following call panics, it indicates UnimplementedConfigCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigCenter_ServiceDesc, srv)
}

func _ConfigCenter_PublishConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).PublishConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_PublishConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).PublishConfig(ctx, req.(*PublishConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigCenter_ServiceDesc is the grpc.ServiceDesc for ConfigCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configcenter.v1.ConfigCenter",
	HandlerType: (*ConfigCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishConfig",
			Handler:    _ConfigCenter_PublishConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configcenter/v1/config_center.proto",
}
